(function(A){
 const R=A.Core.Registry,G=A.Core.Graders,SVG=A.Renderers.SVG,MR=A.Renderers.Math;
 const S=(...x)=>x.map(text=>({text}));
 const choose=(Random,items)=>Random.choice(items);
 R.register({id:'7.1.perimeter-rectangle',chapter:7,section:'7.1',title:'Perimeter of a rectangle',generate:({difficulty,Random})=>{const l=Random.int(3,20),w=Random.int(2,15),ans=2*(l+w);return {promptHtml:`Find the perimeter of the rectangle. ${SVG.rectangle(l+' cm',w+' cm')}`,answer:String(ans),grader:G.numeric(ans),solution:[{html:MR.equationLines([`P = 2(l + w)`,`P = 2(${l} + ${w})`,`P = 2(${l+w})`,`P = ${ans} cm`],'Use the perimeter formula')} ,{text:`Answer: ${ans} cm.`}]};}});
 R.register({id:'7.1.area-rectangle',chapter:7,section:'7.1',title:'Area of a rectangle',generate:({difficulty,Random})=>{const l=Random.int(3,20),w=Random.int(2,15),ans=l*w;return {promptHtml:`Find the area of the rectangle. ${SVG.rectangle(l+' cm',w+' cm')}`,answer:String(ans),grader:G.numeric(ans),solution:[{html:MR.equationLines([`A = l × w`,`A = ${l} × ${w}`,`A = ${ans} cm²`],'Use the area formula')} ,{text:`Answer: ${ans} cm².`}]};}});
 R.register({id:'7.2.missing-side-area',chapter:7,section:'7.2',title:'Rectangle with a given area',generate:({difficulty,Random})=>{const l=Random.int(3,15),w=Random.int(2,12),area=l*w;const prompt=choose(Random,[`A rectangle has area ${area} cm² and length ${l} cm. What is its width?`,`A rectangular poster has an area of ${area} cm² and a length of ${l} cm. What is its width?`,`A rectangular tile covers ${area} cm². If its length is ${l} cm, how wide is it?`,`A small rectangular garden model has area ${area} cm² and length ${l} cm. Find its width.`]);return {prompt,answer:String(w),grader:G.numeric(w),animation:{type:'rectangle-missing-side',length:l,width:w,area},solution:[{html:MR.equationLines([`A = l × w`,`${area} = ${l} × x`],'Let the missing width be x')},{html:MR.equationLines([`${area} ÷ ${l} = x`,`x = ${w} cm`],'Solve for x')} ,{text:`Answer: width = ${w} cm.`}]};}});
 R.register({id:'7.3.angle-type',chapter:7,section:'7.3',title:'Classify an angle',generate:({difficulty,Random})=>{const angle=Random.choice([30,45,60,90,110,125,150,180,225,270]),type=angle<90?'acute':angle===90?'right':angle<180?'obtuse':angle===180?'straight':'reflex';return {prompt:`An angle measures ${angle}°. Is it acute, right, obtuse, straight, or reflex?`,answer:type,grader:G.text(type),solution:[{html:MR.calcTable([[`${angle}°`, angle<90?'less than 90°':angle===90?'equal to 90°':angle<180?'between 90° and 180°':angle===180?'equal to 180°':'greater than 180°'],['Type', type]],['Measure','Reason'])},{text:`Answer: ${type} angle.`}]};}});
 R.register({id:'7.4.metric-conversion',chapter:7,section:'7.4',title:'Convert metric length units',generate:({difficulty,Random})=>{const cases=[['km','m',1000],['m','cm',100],['cm','mm',10],['m','mm',1000]],c=Random.choice(cases),n=Random.int(2,25),ans=n*c[2];return {prompt:`Convert ${n} ${c[0]} to ${c[1]}.`,answer:String(ans),grader:G.numeric(ans),solution:[{html:MR.equationLines([`1 ${c[0]} = ${c[2]} ${c[1]}`,`${n} ${c[0]} = ${n} × ${c[2]} ${c[1]}`,`${n} ${c[0]} = ${ans} ${c[1]}`],'Multiply because you are changing to a smaller unit')} ,{text:`Answer: ${ans} ${c[1]}.`}]};}});
})(MathApp);
