(function(A){
 const R=A.Core.Registry,G=A.Core.Graders,SVG=A.Renderers.SVG;
 const S=(...x)=>x.map(text=>({text}));
 R.register({id:'8.1.line-relationship',chapter:8,section:'8.1',title:'Parallel / perpendicular / intersecting',generate:({difficulty,Random})=>{const type=Random.choice(['parallel','perpendicular','intersecting']);const defs={parallel:'Two lines run in the same direction and never meet.',perpendicular:'Two lines meet to form a right angle.',intersecting:'Two lines meet, but not at a right angle.'};return {prompt:`Which word describes these lines? ${defs[type]}`,answer:type,grader:G.text(type),animation:{type:'line-relationship-visual',relationship:type},solution:S(`Read the description carefully: ${defs[type]}`,type==='parallel'?`Because the lines never meet and remain the same distance apart, they are parallel.`:type==='perpendicular'?`Because the lines meet at a 90° right angle, they are perpendicular.`:`Because the lines meet but do not form a right angle, they are intersecting.`,`Answer: ${type}.`)};}});
 const solids={cube:[6,12,8], 'rectangular prism':[6,12,8], cylinder:[3,2,0], 'square pyramid':[5,8,5]};
 R.register({id:'8.2.solid-properties',chapter:8,section:'8.2',title:'Faces, edges, and vertices',generate:({difficulty,Random})=>{const name=Random.choice(Object.keys(solids)),[faces,edges,vertices]=solids[name],ask=Random.choice(['faces','edges','vertices']),ans={faces,edges,vertices}[ask];return {prompt:`How many ${ask} does a ${name} have?`,answer:String(ans),grader:G.numeric(ans),animation:{type:'solid-properties-visual',solid:name,ask,counts:{faces,edges,vertices}},solution:S(`Identify the solid as a ${name}.`,`Count or recall each feature: faces = ${faces}, edges = ${edges}, vertices = ${vertices}.`,`The question asks for ${ask}.`,`Therefore the answer is ${ans}.`)};}});
 R.register({id:'8.3.plot-point',chapter:8,section:'8.3',title:'Read coordinates in first quadrant',generate:({difficulty,Random})=>{const p=[Random.int(1,6),Random.int(1,6)];return {promptHtml:`What are the coordinates of point A? ${SVG.coordinateGrid(p)}`,answer:`${p[0]},${p[1]}`,grader:(input)=>String(input).replace(/[()\s]/g,'')===`${p[0]},${p[1]}`,animation:{type:'coordinate-read-visual',point:p,label:'A'},solution:S(`Start at the origin (0, 0).`,`Move horizontally to point A; this gives x = ${p[0]}.`,`Then read the vertical position; this gives y = ${p[1]}.`,`Write coordinates in the order (x, y).`,`Point A is (${p[0]}, ${p[1]}).`),answerPreview:'Enter as x,y — for example 3,5'};}});
 R.register({id:'8.3.translate-point',chapter:8,section:'8.3',title:'Translate a point',generate:({difficulty,Random})=>{const p=[Random.int(2,5),Random.int(2,5)],dx=Random.choice([-2,-1,1,2]),dy=Random.choice([-2,-1,1,2]),q=[p[0]+dx,p[1]+dy];if(q[0]<0||q[1]<0||q[0]>7||q[1]>7)return A.Core.Registry.generate('8.3.translate-point',difficulty);return {prompt:`Point A is (${p[0]}, ${p[1]}). Translate it ${Math.abs(dx)} unit${Math.abs(dx)>1?'s':''} ${dx>0?'right':'left'} and ${Math.abs(dy)} unit${Math.abs(dy)>1?'s':''} ${dy>0?'up':'down'}. What are the new coordinates?`,answer:`${q[0]},${q[1]}`,grader:(input)=>String(input).replace(/[()\s]/g,'')===`${q[0]},${q[1]}`,animation:{type:'coordinate-translate-visual',point:p,translated:q,dx,dy,label:'A'},solution:S(`Horizontal move changes x: ${p[0]} ${dx>=0?'+':'−'} ${Math.abs(dx)} = ${q[0]}.`,`Vertical move changes y: ${p[1]} ${dy>=0?'+':'−'} ${Math.abs(dy)} = ${q[1]}.`,`New point: (${q[0]}, ${q[1]}).`)};}});
 R.register({id:'8.4.identify-transformation',chapter:8,section:'8.4',title:'Identify a transformation',generate:({difficulty,Random})=>{const t=Random.choice(['translation','rotation','reflection']),clues={translation:'The shape slides without turning or flipping.',rotation:'The shape turns around a point.',reflection:'The shape flips across a line like a mirror image.'};let anim; if(t==='translation'){const base=[[1,1],[2,3],[3,1]],dx=Random.choice([2,3]),dy=Random.choice([1,2]);anim={type:'transformation-visual',kind:t,base,transformed:base.map(([x,y])=>[x+dx,y+dy]),dx,dy};} else if(t==='rotation'){const center=[4,4],base=[[5,4],[6,5],[6,3]];anim={type:'transformation-visual',kind:t,base,center,transformed:base.map(([x,y])=>[center[0]-(y-center[1]),center[1]+(x-center[0])])};} else {const mirrorX=4,base=[[1,2],[2,4],[3,2]];anim={type:'transformation-visual',kind:t,base,mirror:{axis:'vertical',value:mirrorX},transformed:base.map(([x,y])=>[2*mirrorX-x,y])};}return {prompt:`Name the transformation: ${clues[t]}`,answer:t,grader:G.text(t),animation:anim,solution:S(`${clues[t]}`,t==='translation'?`A translation changes position but keeps the same orientation.`:t==='rotation'?`A rotation changes orientation by turning around a fixed point.`:`A reflection produces a mirror image across a line.`,`Therefore the transformation is a ${t}.`)};}});
})(MathApp);
