(function(A){
 const R=A.Core.Registry,G=A.Core.Graders;
 const S=(...x)=>x.map(text=>({text}));
 const choose=(Random,items)=>Random.choice(items);
 R.register({id:'11.1.sequence',chapter:11,section:'11.1',title:'Sequential instructions',generate:({difficulty,Random})=>{const x=Random.int(1,3),y=Random.int(1,3),moves=[['right',Random.int(1,3)],['up',Random.int(1,3)]],fx=x+moves[0][1],fy=y+moves[1][1];const prompt=choose(Random,[`A robot starts at (${x}, ${y}). It moves ${moves[0][1]} square(s) right, then ${moves[1][1]} square(s) up. Where does it finish?`,`A game sprite begins at (${x}, ${y}). The code moves it ${moves[0][1]} square(s) right and then ${moves[1][1]} square(s) up. What are its final coordinates?`,`A coding character starts at (${x}, ${y}). Execute these instructions in order: move ${moves[0][1]} right; move ${moves[1][1]} up. Where does the character end?`]);return {prompt,answer:`${fx},${fy}`,grader:(input)=>String(input).replace(/[()\s]/g,'')===`${fx},${fy}`,solution:S(`Start at (${x}, ${y}).`,`Moving ${moves[0][1]} right changes only x: ${x} + ${moves[0][1]} = ${fx}. The position is now (${fx}, ${y}).`,`Moving ${moves[1][1]} up changes only y: ${y} + ${moves[1][1]} = ${fy}.`,`Final position: (${fx}, ${fy}).`)};}});
 R.register({id:'11.2.simplify-code',chapter:11,section:'11.2',title:'Simplify repeated instructions',generate:({difficulty,Random})=>{const times=Random.int(3,6);const repeated=Array(times).fill('move 1 step forward').join('; ');const prompt=choose(Random,[`Simplify this code: ${repeated}.`,`A sprite has these repeated commands: ${repeated}. Rewrite them using a repeat instruction.`,`The same command appears ${times} times in a row: ${repeated}. How can the code be shortened?`]);return {prompt,answer:`repeat ${times}`,grader:G.oneOf([`repeat ${times}`,`repeat ${times} times`,`move ${times} steps forward`]),solution:S(`Count the repeated commands: “move 1 step forward” appears ${times} times.`,`The repeated block can be replaced by a loop: repeat ${times} times { move 1 step forward }.`,`Because 1 step is repeated ${times} times, total movement is ${times} × 1 = ${times} steps.`,`Equivalent simplified instruction: move ${times} steps forward.`)};}});
 R.register({id:'11.3.code-blocks',chapter:11,section:'11.3',title:'Predict code-block output',generate:({difficulty,Random})=>{const n=Random.int(2,6),step=Random.int(1,4),ans=n*step;return {prompt:`A code block says: repeat ${n} times { move ${step} steps }. How many steps does the sprite move in total?`,answer:String(ans),grader:G.numeric(ans),solution:S(`The repeat block runs ${n} times.`,`Each run moves ${step} steps.`,`Total movement = repetitions × steps per repetition.`,`${n} × ${step} = ${ans}.`,`Answer: ${ans} total steps.`)};}});
 R.register({id:'11.4.conditional',chapter:11,section:'11.4',title:'Conditional statement',generate:({difficulty,Random})=>{const score=Random.int(0,20),threshold=10,ans=score>=threshold?'move':'stay';return {prompt:`Code: IF score ≥ ${threshold}, THEN move; ELSE stay. If score = ${score}, what happens?`,answer:ans,grader:G.oneOf([ans]),solution:S(`Evaluate the condition: is ${score} ≥ ${threshold}?`,`${score} ${score>=threshold?'≥':'<'} ${threshold}, so the condition is ${score>=threshold?'true':'false'}.`,`${score>=threshold?'Use the THEN branch: move.':'Use the ELSE branch: stay.'}`,`Answer: the sprite will ${ans}.`)};}});
 R.register({id:'11.5.scratch-logic',chapter:11,section:'11.5',title:'Scratch-style logic',generate:({difficulty,Random})=>{const n=Random.int(2,5),turn=Random.choice([90,180]),ans=turn===90?'quarter turn':'half turn';return {prompt:`A Scratch-style script repeats: move 10 steps, turn ${turn}°. What kind of turn is ${turn}°?`,answer:ans,grader:G.text(ans),solution:S(`A full turn is 360°.`,`Compare ${turn}° with 360°: ${turn}/360 = ${turn/360}.`,`${turn}° is therefore a ${ans}.`,`Answer: ${ans}.`)};}});
})(MathApp);
