(function(A){
 const R=A.Core.Registry,G=A.Core.Graders;
 const S=(...x)=>x.map(text=>({text}));
 const choose=(Random,items)=>Random.choice(items);
 R.register({id:'10.1.communicate-method',chapter:10,section:'10.1',title:'Communicate mathematical thinking',generate:({difficulty,Random})=>{const a=Random.int(20,90),b=Random.int(10,40);const prompt=choose(Random,[`Explain in one or two sentences how you would find ${a} + ${b} without a calculator.`,`A classmate asks how to calculate ${a} + ${b} mentally. Explain a strategy clearly enough that they could follow it.`,`Describe a mental-math method for finding ${a} + ${b}. Show how you break apart at least one number.`]);return {prompt,answer:'Self-check',grader:G.selfCheck(),selfCheck:true,animation:{type:'mental-addition-strategy',a,b,tens:Math.floor(b/10)*10,ones:b%10,total:a+b},solution:S(`One clear strategy is to break ${b} into tens and ones.`,`For example, ${b} = ${Math.floor(b/10)*10} + ${b%10}.`,`First add the tens: ${a} + ${Math.floor(b/10)*10} = ${a+Math.floor(b/10)*10}.`,`Then add the ones: ${a+Math.floor(b/10)*10} + ${b%10} = ${a+b}.`,`A complete explanation should show both the strategy and the result ${a+b}.`)};}});
 R.register({id:'10.2.represent-number',chapter:10,section:'10.2',title:'Represent a number in another way',generate:({difficulty,Random})=>{const n=Random.int(120,999);const h=Math.floor(n/100),t=Math.floor((n%100)/10),o=n%10;return {prompt:`Represent ${n} using hundreds, tens, and ones.`,answer:`${h},${t},${o}`,grader:(input)=>String(input).replace(/\s/g,'')===`${h},${t},${o}`,animation:{type:'base-ten-representation',n,h,t,o},solution:S(`Break ${n} into place values.`,`${h} hundreds = ${h*100}.`,`${t} tens = ${t*10}.`,`${o} ones = ${o}.`,`Check: ${h*100} + ${t*10} + ${o} = ${n}.`,`Answer: ${h} hundreds, ${t} tens, ${o} ones.`),answerPreview:'Enter hundreds,tens,ones — for example 3,4,2'};}});
 R.register({id:'10.3.connect-concepts',chapter:10,section:'10.3',title:'Connect two representations',generate:({difficulty,Random})=>{const p=Random.choice([25,50,75]),frac={25:'1/4',50:'1/2',75:'3/4'}[p];return {prompt:`Which fraction is equivalent to ${p}%?`,answer:frac,grader:G.fraction(A.Math.Fraction.parse(frac)),animation:{type:'percent-to-fraction-visual',p,frac},solution:S(`${p}% means ${p} out of 100, so write ${p}/100.`,`Find a common factor of ${p} and 100 and divide both by it.`,`After simplifying, ${p}/100 = ${frac}.`,`Answer: ${frac}.`)};}});
 R.register({id:'10.4.reasoning',chapter:10,section:'10.4',title:'Reason and justify',generate:({difficulty,Random})=>{const claim=Random.bool(),a=Random.int(20,80),b=Random.int(2,9),rounded=Math.round(a/10)*10;const prompt=choose(Random,[`A student says “${a} rounded to the nearest ten is ${rounded}.” Explain why this is correct.`,`Someone rounded ${a} to ${rounded} to the nearest ten. Justify the result using the ones digit.`,`Prove that ${rounded} is the correct nearest-ten estimate for ${a}. What digit controls the rounding decision?`]);return {prompt,answer:'Self-check',grader:G.selfCheck(),selfCheck:true,animation:{type:'rounding-justify-visual',a,rounded,ones:a%10},solution:S(`We are rounding ${a} to the nearest ten, so inspect its ones digit: ${a%10}.`,`${a%10>=5?'Because the ones digit is 5 or greater, increase the tens digit by 1.':'Because the ones digit is less than 5, keep the tens digit the same.'}`,`Replace the ones digit with 0.`,`This gives ${rounded}.`,`Therefore the statement is correct: ${a} rounds to ${rounded}.`)};}});
})(MathApp);
