(function(A){
 const R=A.Core.Registry,G=A.Core.Graders,SVG=A.Renderers.SVG,F=A.Math.Fraction,U=A.Math.Utils,MR=A.Renderers.Math;
 const S=(...x)=>x.map(text=>({text}));
 const choose=(Random,items)=>Random.choice(items);
 R.register({id:'9.1.sample-population',chapter:9,section:'9.1',title:'Sample or population',generate:({difficulty,Random})=>{const isSample=Random.bool();const pairs=[['A school surveys 40 randomly chosen Grade 5 students about recess.','A school asks every Grade 5 student about recess.'],['A town asks 75 randomly selected residents about a new park.','A town asks every resident about a new park.'],['A coach asks 12 randomly chosen players about practice times.','A coach asks every player on the team about practice times.'],['A library asks 30 randomly selected visitors about favourite genres.','A library asks every visitor that day about favourite genres.']];const pair=choose(Random,pairs),scenario=isSample?pair[0]:pair[1];const ans=isSample?'sample':'population';return {prompt:`Does this describe a sample or a population? ${scenario}`,answer:ans,grader:G.text(ans),animation:{type:'sample-population-visual',isSample,scenario},solution:[{html:MR.calcTable([['Group of interest','All Grade 5 students'],['Who was asked?',isSample?'Only some students':'Every student'],['Answer',ans]],['Think about','Reason'])}]};}});
 R.register({id:'9.2.interpret-table',chapter:9,section:'9.2',title:'Interpret grouped data',generate:({difficulty,Random})=>{const vals=[Random.int(3,15),Random.int(3,15),Random.int(3,15),Random.int(3,15)],labels=['Red','Blue','Green','Yellow'],max=Math.max(...vals),idx=vals.indexOf(max);return {prompt:`Votes are Red ${vals[0]}, Blue ${vals[1]}, Green ${vals[2]}, Yellow ${vals[3]}. Which colour has the most votes?`,answer:labels[idx],grader:G.text(labels[idx]),animation:{type:'grouped-data-visual',labels,vals,maxIndex:idx},solution:[{html:MR.calcTable(labels.map((lab,i)=>[lab,String(vals[i])]),['Colour','Votes'])},{text:`The largest number of votes is ${max}, so the answer is ${labels[idx]}.`}]};}});
 R.register({id:'9.3.bar-graph-read',chapter:9,section:'9.3',title:'Read a bar graph',generate:({difficulty,Random})=>{const labels=['A','B','C','D'],vals=labels.map(()=>Random.int(2,12)),i=Random.int(0,3);return {promptHtml:`How many votes does category ${labels[i]} have? ${SVG.barChart(labels,vals,'Class Survey')}`,answer:String(vals[i]),grader:G.numeric(vals[i]),animation:{type:'bar-read-visual',labels,vals,target:i,title:'Class Survey'},solution:[{html:SVG.barChart(labels,vals,'Class Survey')},{text:`Locate category ${labels[i]} and read the height of its bar. It reaches ${vals[i]}.`}]};}});
 R.register({id:'9.4.compare-bars',chapter:9,section:'9.4',title:'Compare values in a graph',generate:({difficulty,Random})=>{const labels=['Mon','Tue','Wed','Thu'],vals=labels.map(()=>Random.int(3,15)),a=Random.int(0,2),b=a+1,ans=Math.abs(vals[a]-vals[b]);return {promptHtml:`How many more or fewer separate ${labels[a]} and ${labels[b]}? Give the absolute difference. ${SVG.barChart(labels,vals,'Books Read')}`,answer:String(ans),grader:G.numeric(ans),animation:{type:'compare-bars-visual',labels,vals,a,b,ans,title:'Books Read'},solution:[{html:SVG.barChart(labels,vals,'Books Read')},{html:MR.equationLines([`${labels[a]} = ${vals[a]}`,`${labels[b]} = ${vals[b]}`,`|${vals[a]} - ${vals[b]}| = ${ans}`],'Read both bars, then subtract')} ,{text:`Answer: ${ans}.`}]};}});
 R.register({id:'9.5.theoretical-probability',chapter:9,section:'9.5',title:'Theoretical probability',generate:({difficulty,Random})=>{const total=Random.int(4,10),fav=Random.int(1,total-1),f=new F(fav,total).simplify(),g=U.gcd(fav,total);const prompts=[`A bag has ${total} equally likely cards, and ${fav} are winning cards. What is the theoretical probability of drawing a winning card? Give a simplified fraction.`,`A spinner has ${total} equal sections, and ${fav} of them are blue. What is the probability of landing on blue? Give a simplified fraction.`,`There are ${total} equally likely numbered tiles, and ${fav} of them meet the winning condition. What is the theoretical probability of selecting a winning tile?`,`A box contains ${total} equally likely tokens, ${fav} of which are stars. What is the probability of drawing a star? Give a simplified fraction.`];return {prompt:choose(Random,prompts),answer:f.toString(),grader:G.fraction(f,{requireSimplest:true}),animation:{type:'theoretical-probability-visual',total,fav,simplified:[f.n,f.d]},solution:[{html:MR.equationLines([`P(event) = favorable outcomes / total outcomes`,`P = ${fav}/${total}`,`P = (${fav} ÷ ${g}) / (${total} ÷ ${g})`,`P = ${f.n}/${f.d}`],'Write the probability as a fraction and simplify')} ,{text:`Answer: ${f.n}/${f.d}.`}]};}});
 R.register({id:'9.5.experimental-probability',chapter:9,section:'9.5',title:'Experimental probability',generate:({difficulty,Random})=>{const trials=Random.choice([20,30,40,50]),success=Random.int(2,trials-2),f=new F(success,trials).simplify(),g=U.gcd(success,trials);const prompts=[`In ${trials} trials, an event happened ${success} times. What is the experimental probability? Give a simplified fraction.`,`A spinner was spun ${trials} times and landed on red ${success} times. What is the experimental probability of red?`,`A coin-like game was played ${trials} times and the target result occurred ${success} times. Find the experimental probability.`,`A student tested a random event ${trials} times and recorded ${success} successes. What is the experimental probability?`];return {prompt:choose(Random,prompts),answer:f.toString(),grader:G.fraction(f,{requireSimplest:true}),animation:{type:'experimental-probability-visual',trials,success,simplified:[f.n,f.d]},solution:[{html:MR.equationLines([`experimental probability = successes / total trials`,`= ${success}/${trials}`,`= (${success} ÷ ${g}) / (${trials} ÷ ${g})`,`= ${f.n}/${f.d}`],'Use the data from the experiment')} ,{text:`Answer: ${f.n}/${f.d}.`}]};}});
})(MathApp);
