(function(A){
 const R=A.Core.Registry,G=A.Core.Graders,U=A.Math.Utils;
 const S=(...x)=>x.map(text=>({text}));
 const choose=(Random,items)=>Random.choice(items);
 R.register({id:'5.1.next-term-add',chapter:5,section:'5.1',title:'Add/subtract pattern rule',generate:({difficulty,Random})=>{const start=Random.int(2,50),delta=Random.choice([2,3,4,5,6,7,8,10])*(Random.bool(.25)?-1:1),arr=[0,1,2,3].map(i=>start+i*delta),ans=start+4*delta;return {prompt:`Find the next term: ${arr.join(', ')}, …`,answer:String(ans),grader:G.numeric(ans),animation:{type:'pattern-arrows',mode:'add',terms:arr,delta,answer:ans},solution:S(`Find the difference between consecutive terms: ${arr[1]} − ${arr[0]} = ${delta}.`,`Check again: ${arr[2]} − ${arr[1]} = ${delta}.`,`The repeated rule is ${delta>=0?'add':'subtract'} ${Math.abs(delta)}.`,`Apply it to the last shown term: ${arr[3]} ${delta>=0?'+':'−'} ${Math.abs(delta)} = ${ans}.`,`Answer: ${ans}.`)};}});
 R.register({id:'5.1.next-term-multiply',chapter:5,section:'5.1',title:'Multiplicative pattern',generate:({difficulty,Random})=>{const factor=Random.choice([2,3,4,5]),start=Random.int(1,5),arr=[start];for(let i=1;i<4;i++)arr.push(arr[i-1]*factor);const ans=arr[3]*factor;return {prompt:`Find the next term: ${arr.join(', ')}, …`,answer:String(ans),grader:G.numeric(ans),animation:{type:'pattern-arrows',mode:'multiply',terms:arr,factor,answer:ans},solution:S(`Check the pattern: ${arr[0]} × ${factor} = ${arr[1]}.`,`Then ${arr[1]} × ${factor} = ${arr[2]}, so the same multiplication rule continues.`,`Apply the rule to the last term: ${arr[3]} × ${factor} = ${ans}.`,`Answer: ${ans}.`)};}});
 R.register({id:'5.1.rule-description',chapter:5,section:'5.1',title:'Describe a pattern rule',generate:({difficulty,Random})=>{const delta=Random.choice([2,3,4,5,6,10]),start=Random.int(1,25),arr=[0,1,2,3].map(i=>start+i*delta),answer=`add ${delta}`;return {prompt:`Describe the rule for this pattern: ${arr.join(', ')}, …`,answer,grader:G.oneOf([`add ${delta}`,`+${delta}`,`plus ${delta}`,`increase by ${delta}`]),animation:{type:'pattern-rule-discovery',terms:arr,delta},solution:S(`Compare the first two terms: ${arr[1]} − ${arr[0]} = ${delta}.`,`Check the next pair: ${arr[2]} − ${arr[1]} = ${delta}.`,`The difference is constant, so the rule repeats each time.`,`Rule: add ${delta}.`)};}});
 R.register({id:'5.2.table-pattern',chapter:5,section:'5.2',title:'Represent a relationship in a table',generate:({difficulty,Random})=>{const rate=Random.int(2,12),x=Random.choice([5,6,8,10,12]),pairs=[1,2,3,4].map(n=>[n,n*rate]),ans=x*rate;const table=pairs.map(p=>`${p[0]}→${p[1]}`).join(', ');const prompt=choose(Random,[`A table follows the relationship ${table}. If the input is ${x}, what is the output?`,`A delivery job pays $${rate} for each bundle delivered. The table starts 1→${rate}, 2→${2*rate}, 3→${3*rate}, 4→${4*rate}. How much is paid for ${x} bundles?`,`A recipe uses ${rate} cups of water for every scoop of mix. The pattern is 1→${rate}, 2→${2*rate}, 3→${3*rate}, 4→${4*rate}. How many cups are needed for ${x} scoops?`,`A game costs $${rate} each. The cost pattern is 1→${rate}, 2→${2*rate}, 3→${3*rate}, 4→${4*rate}. What is the cost of ${x} games?`]);return {prompt,answer:String(ans),grader:G.numeric(ans),animation:{type:'rule-machine',rate,pairs,x,answer:ans},solution:S(`Use a known pair to find the relationship: 1 → ${rate}.`,`Check another pair: 2 × ${rate} = ${2*rate}.`,`So the rule is output = input × ${rate}.`,`For input ${x}: ${x} × ${rate} = ${ans}.`,`Answer: ${ans}.`)};}});
})(MathApp);
